#!/bin/zsh

# useful for debugging
# set -ex

PROFILE="$1"

if [ "$PROFILE" = "work" ]; then
	IS_PERSONAL=false
elif [ "$PROFILE" = "home" ]; then
	IS_PERSONAL=true
else
	echo "no profile argument passed, please pass \"home\" or \"work\" as the first argument"
	exit 1
fi

command_exists() {
	type "$1" &> /dev/null ;
}

if ! command_exists nix ; then
	echo "Installing Nix"
	curl -L https://github.com/NixOS/experimental-nix-installer/releases/download/0.27.0/nix-installer.sh | sh -s -- install
fi
if ! command_exists devenv ; then
	echo "Installing devenv"
	nix profile install nixpkgs#devenv
fi

echo "Installing base homebrew packages"
brew bundle --file "$HOME/.dotfiles/setup/base/Brewfile"

if [ "$IS_PERSONAL" = true ]; then
	echo "Installing home homebrew packages"
	brew bundle --file "$HOME/.dotfiles/setup/home/Brewfile"
else
	echo "Installing work homebrew packages"
	brew bundle --file "$HOME/.dotfiles/setup/work/Brewfile"
fi

# check for fish in list of valid shells
cat /etc/shells | grep fish
if [[ $? -eq 1 ]]; then
	echo "adding fish to list of allowable shells and setting as user shell"
	echo "/opt/homebrew/bin/fish" | sudo tee -a /etc/shells
	chsh -s /opt/homebrew/bin/fish
	echo 'fisher update' | fish
fi

if [ "$IS_PERSONAL" = true ]; then
	fish "$HOME/.dotfiles/setup/home_setup.fish"
else
	fish "$HOME/.dotfiles/setup/work_setup.fish"
fi

echo "GitHub auth status:"
gh auth status