#!/bin/zsh

# useful for debugging
# set -ex

PROFILE="$1"

if [ "$PROFILE" = "work" ]; then
	IS_PERSONAL=false
elif [ "$PROFILE" = "home" ]; then
	IS_PERSONAL=true
else
	echo "no profile argument passed, please pass \"home\" or \"work\" as the first argument"
	exit 1
fi

command_exists() {
	type "$1" &> /dev/null ;
}

if ! command_exists nix ; then
	curl -L https://github.com/NixOS/experimental-nix-installer/releases/download/0.27.0/nix-installer.sh | sh -s -- install
fi

# TODO add devenv

brew bundle --file "$HOME/.dotfiles/setup/base/Brewfile"

if [ "$IS_PERSONAL" = true ]; then
	brew bundle --file "$HOME/.dotfiles/setup/home/Brewfile"
else
	brew bundle --file "$HOME/.dotfiles/setup/work/Brewfile"
	# TODO add naws setup
	npm config set @ffa:registry https://artifactory.flexport.io/artifactory/api/npm/ffa-infra-npm-dev-local
	npm install -g @ffa/naws-cli
	git lfs install
fi
fisher update

# check for fish in list of valid shells
cat /etc/shells | grep fish
if [[ $? -eq 1 ]]; then
	echo "adding fish to list of allowable shells and setting as user shell"
	echo "/opt/homebrew/bin/fish" | sudo tee -a /etc/shells
	chsh -s /opt/homebrew/bin/fish
fi

gh auth status
