#!/bin/bash

echo "Stowing all dotfiles into home directory. Note this requires all conflicting dotfiles to be deleted. It is recommended to backup existing dotfiles in the home directory in case of issues."

# directories in this repo containing dotfiles
dirs=(
	bash
	zen
	kitty
	hyprland
	fish
	zellij
	gh
	git
	pipewire
)

if [ -d "$HOME/.dotfiles" ]; then
	echo "Using ~/.dotfiles as stow directory"
else
	echo "Please clone this repo into the home directory and re-run this script"
	exit 1
fi

# -v Verbose
# -R Restow (aka delete existing stows first)
# -d Set stow directory
# --dotfiles Change dot-<name> files to .<name> when stowing
# -t target directory to stow into
# $dir subdirectory of dotfiles repo to symlink dotfiles from into target
for dir in ${dirs[@]}; do
	stow -d "$HOME/.dotfiles" -v -R --dotfiles -t "$HOME" $dir
done

echo "Finished stowing dotfiles, use the alias command \`restow <dotfiles subdir>\` to re-stow a particular directory in the future"
