#!/bin/bash

# directories in this repo containing dotfiles
# TODO add personal vs work mac
mac_dirs=(
	kitty
	fish
	zellij
)
# TODO add zsh and maybe bash
# gh git add once figure out how need to change for work
	
arch_dirs=(
	bash
	kitty
	hyprland
	fish
	zellij
	gh
	git
	pipewire
)

if [ -d "$HOME/.dotfiles" ]; then
	echo "Using ~/.dotfiles as stow directory"
else
	echo "Please clone this repo into the home directory and re-run this script"
	exit 1
fi

if [ "$1" = "arch" ]; then
	echo "Stowing arch dotfiles into home directory. Note this requires all conflicting dotfiles to be deleted. It is recommended to backup existing dotfiles in the home directory in case of issues."
	dirs=$arch_dirs
elif [ "$1" = "mac" ]; then
	echo "Stowing mac dotfiles into home directory. Note this requires all conflicting dotfiles to be deleted. It is recommended to backup existing dotfiles in the home directory in case of issues."
	dirs=$mac_dirs
else
	echo "Unrecognized system, please specify \"arch\" or \"mac\" as first argument"
	exit 1
fi

# -v Verbose
# -R Restow (aka delete existing stows first)
# -d Set stow directory
# --dotfiles Change dot-<name> files to .<name> when stowing
# -t target directory to stow into
# $dir subdirectory of dotfiles repo to symlink dotfiles from into target
for dir in ${dirs[@]}; do
	stow -d "$HOME/.dotfiles" -v -R --dotfiles -t "$HOME" $dir
done

echo "Finished stowing dotfiles, use the alias command \`restow <dotfiles subdir>\` to re-stow a particular directory in the future"
